In [2]:
import pandas as pd
import numpy as np

In [56]:
ele = pd.read_csv('/Users/miana/Downloads/Neo4j_clean_data/elementary_school_district_wkt.csv')

In [57]:
ele = ele.iloc[:,1:]

In [58]:
ele = ele.rename(columns = {'ELSDLEA' : 'SDLEA'})

In [59]:
ele['school_district_type'] = 'Elementary'

In [60]:
ele.head(10)

,STATEFP,SDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,g_wkt_final,school_district_type
0,27,388,2700388,Round Lake-Brewster Public Schools,0,PK,8,G5400,NaN,E,355350345,6452268,43.634020,-95.473212,"POLYGON ((-95.574101 43.523965, -95.574096 43....",Elementary
1,27,7110,2707110,Browns Valley Public School District,0,PK,8,G5400,NaN,E,120256291,18198228,45.651305,-96.750555,"POLYGON ((-96.856815 45.605556, -96.856758 45....",Elementary
2,27,15540,2715540,Ivanhoe Public School District,0,PK,6,G5400,NaN,E,374419867,9590646,44.467605,-96.231076,"MULTIPOLYGON (((-96.10014 44.510503, -96.09554...",Elementary
3,27,17460,2717460,Lake Benton Public School District,0,PK,6,G5400,NaN,E,364178280,11977246,44.291559,-96.333585,"MULTIPOLYGON (((-96.28539699999999 44.185446, ...",Elementary
4,27,18390,2718390,Lynd Public School District,0,PK,8,G5400,NaN,E,186657821,816941,44.403305,-95.927624,"POLYGON ((-96.04873099999999 44.426212, -96.04...",Elementary
5,27,21210,2721210,Milroy Public School District,0,PK,8,G5400,NaN,E,225626226,1032089,44.434415,-95.530739,"MULTIPOLYGON (((-95.480605 44.380759999999995,...",Elementary
6,27,33720,2733720,Nett Lake Public School District,0,PK,6,G5400,NaN,E,250319140,29530604,48.129935,-93.176919,"POLYGON ((-93.357889 48.07038, -93.357821 48.0...",Elementary
7,27,28960,2728960,Pine Point Public School District,0,KG,8,G5400,NaN,E,10707431,2071546,46.997586,-95.395388,"POLYGON ((-95.42335299999999 47.005607, -95.42...",Elementary

In [51]:
sec = pd.read_csv('/Users/miana/Downloads/Neo4j_clean_data/secondary_school_district_wkt.csv')

In [52]:
sec =sec.iloc[:,1:]

In [53]:
sec = sec.rename(columns = {'SCSDLEA' : 'SDLEA'})

In [54]:
sec['school_district_type'] = 'Secondary'

In [55]:
sec.head(10)

,STATEFP,SDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,g_wkt_final,school_district_type
0,27,27001,2727001,Park Rapids Public School District in Pine Poi...,0,9,12,G5410,A,F,10707431,2071546,46.997586,-95.395388,"POLYGON ((-95.42335299999999 47.005607, -95.42...",Secondary
1,27,27002,2727002,Clinton-Graceville-Beardsley-Wheaton-Sisseton/...,0,9,12,G5410,A,F,120256291,18198228,45.651305,-96.750555,"POLYGON ((-96.856815 45.605556, -96.856758 45....",Secondary
2,27,27003,2727003,Minneota-Ivanhoe Public School Districts in Iv...,0,7,12,G5410,A,F,374419867,9590646,44.467605,-96.231076,"MULTIPOLYGON (((-96.10014 44.510503, -96.09554...",Secondary
3,27,27004,2727004,Marshall-Minneota-RTR Public Schools in Lynd (...,0,9,12,G5410,A,F,186657821,816941,44.403305,-95.927624,"POLYGON ((-96.04873099999999 44.426212, -96.04...",Secondary
4,27,27005,2727005,Marshall-Tracy Public Schools in Milroy (9-12),0,9,12,G5410,A,F,225626226,1032089,44.434415,-95.530739,"MULTIPOLYGON (((-95.480605 44.380759999999995,...",Secondary
5,27,27006,2727006,Heron Lake-Okabena-Fulda-Worthington in Round ...,0,9,12,G5410,A,F,355350345,6452268,43.634020,-95.473212,"POLYGON ((-95.574101 43.523965, -95.574096 43....",Secondary
6,27,27007,2727007,St. Louis-Northland in Nett Lake (7-12),0,7,12,G5410,A,F,250319140,29530604,48.129935,-93.176919,"POLYGON ((-93.357889 48.07038, -93.357821 48.0...",Secondary
7,27,99001,2799001,Elkton School District 05-3 in Lake Benton (7-12),0,7,12,G5410,A,F,364178280,11977246,44.291559,-96.333585,"MULTIPOLYGON (((-96.28539699999999 44.185446, ...",Secondary

In [46]:
uni = pd.read_csv('/Users/miana/Downloads/Neo4j_clean_data/unified_school_district_wkt.csv')

In [47]:
uni =uni.iloc[:,1:]

In [48]:
uni = uni.rename(columns = {'UNSDLEA' : 'SDLEA'})

In [49]:
uni['school_district_type'] = 'Unified'

In [50]:
uni.head(10)

,STATEFP,SDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,g_wkt_final,school_district_type
0,27,9440,2709440,Rocori Public School District,0,PK,12,G5420,NaN,E,308115051,21194420,45.466572,-94.461345,"MULTIPOLYGON (((-94.55771299999999 45.401747, ...",Unified
1,27,8910,2708910,Chisholm Public School District,0,PK,12,G5420,NaN,E,172723739,3353522,47.541039,-92.862190,"POLYGON ((-92.939666 47.49004, -92.939545 47.4...",Unified
2,27,11520,2711520,Ely Public School District,0,PK,12,G5420,NaN,E,561100079,85275437,47.907316,-91.932309,"POLYGON ((-92.054327 48.059734, -92.054079 48....",Unified
3,27,12210,2712210,Floodwood Public School District,0,PK,12,G5420,NaN,E,812940084,8542816,46.918073,-92.943190,"POLYGON ((-93.19054299999999 46.97954, -93.190...",Unified
4,27,9540,2709540,Comfrey Public School District,0,KG,12,G5420,NaN,E,319601647,1988199,44.100034,-94.910064,"POLYGON ((-95.090515 44.122564, -95.0882769999...",Unified
5,27,23010,2723010,Mountain Lake Public Schools,0,PK,12,G5420,NaN,E,357431084,2871323,43.938614,-94.953583,"MULTIPOLYGON (((-95.038896 43.918606, -95.0388...",Unified
6,27,16980,2716980,Kasson-Mantorville School District,0,PK,12,G5420,NaN,E,248307426,218175,44.024836,-92.736957,"POLYGON ((-92.81907 43.985102, -92.819064 43.9...",Unified
7,27,287,2700287,Plainview-Elgin-Millville,0,PK,12,G5420,NaN,E,630605124,2684545,44.184728,-92.194171,"MULTIPOLYGON (((-92.007007 44.117323, -92.0070...",Unified
8,27,13590,2713590,Hayfield Public School District,0,PK,12,G5420,NaN,E,513986270,102916,43.844709,-92.818458,"MULTIPOLYGON (((-92.603392 43.893007, -92.6033...",Unified
9,27,130,2700130,Blue Earth Area Public Schools,0,PK,12,G5420,NaN,E,1003399604,9866722,43.663471,-94.061415,"MULTIPOLYGON (((-93.856905 43.681156, -93.8472...",Unified

In [61]:
frames = [ele, sec, uni]

In [62]:
result = pd.concat(frames, sort = False)

In [63]:
len(result)

340

In [64]:
result.head(10)

,STATEFP,SDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,g_wkt_final,school_district_type
0,27,388,2700388,Round Lake-Brewster Public Schools,0,PK,8,G5400,NaN,E,355350345,6452268,43.634020,-95.473212,"POLYGON ((-95.574101 43.523965, -95.574096 43....",Elementary
1,27,7110,2707110,Browns Valley Public School District,0,PK,8,G5400,NaN,E,120256291,18198228,45.651305,-96.750555,"POLYGON ((-96.856815 45.605556, -96.856758 45....",Elementary
2,27,15540,2715540,Ivanhoe Public School District,0,PK,6,G5400,NaN,E,374419867,9590646,44.467605,-96.231076,"MULTIPOLYGON (((-96.10014 44.510503, -96.09554...",Elementary
3,27,17460,2717460,Lake Benton Public School District,0,PK,6,G5400,NaN,E,364178280,11977246,44.291559,-96.333585,"MULTIPOLYGON (((-96.28539699999999 44.185446, ...",Elementary
4,27,18390,2718390,Lynd Public School District,0,PK,8,G5400,NaN,E,186657821,816941,44.403305,-95.927624,"POLYGON ((-96.04873099999999 44.426212, -96.04...",Elementary
5,27,21210,2721210,Milroy Public School District,0,PK,8,G5400,NaN,E,225626226,1032089,44.434415,-95.530739,"MULTIPOLYGON (((-95.480605 44.380759999999995,...",Elementary
6,27,33720,2733720,Nett Lake Public School District,0,PK,6,G5400,NaN,E,250319140,29530604,48.129935,-93.176919,"POLYGON ((-93.357889 48.07038, -93.357821 48.0...",Elementary
7,27,28960,2728960,Pine Point Public School District,0,KG,8,G5400,NaN,E,10707431,2071546,46.997586,-95.395388,"POLYGON ((-95.42335299999999 47.005607, -95.42...",Elementary
0,27,27001,2727001,Park Rapids Public School District in Pine Poi...,0,9,12,G5410,A,F,10707431,2071546,46.997586,-95.395388,"POLYGON ((-95.42335299999999 47.005607, -95.42...",Secondary
1,27,27002,2727002,Clinton-Graceville-Beardsley-Wheaton-Sisseton/...,0,9,12,G5410,A,F,120256291,18198228,45.651305,-96.750555,"POLYGON ((-96.856815 45.605556, -96.856758 45....",Secondary

In [ ]:
# filter school district

In [66]:
HC_school_district = pd.read_csv('/Users/miana/Downloads/Neo4j_clean_data/district_tract.csv')

In [67]:
HC_school_district.head(10)

     LEAID                             NAME_LEA19        TRACT
0  2703180  Anoka-Hennepin Public School District  27053020200
1  2703180  Anoka-Hennepin Public School District  27053020301
2  2703180  Anoka-Hennepin Public School District  27053026707
3  2703180  Anoka-Hennepin Public School District  27053026811
4  2703180  Anoka-Hennepin Public School District  27053026812
5  2703180  Anoka-Hennepin Public School District  27053026814
6  2703180  Anoka-Hennepin Public School District  27053026815
7  2703180  Anoka-Hennepin Public School District  27053026820
8  2703180  Anoka-Hennepin Public School District  27053026822
9  2703180  Anoka-Hennepin Public School District  27053026823

In [68]:
HC_district_wkt = result[result['GEOID'].isin(HC_school_district['LEAID'].tolist())]
HC_district_wkt.head(10)

,STATEFP,SDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,g_wkt_final,school_district_type
125,27,3180,2703180,Anoka-Hennepin Public School District,0,PK,12,G5420,NaN,E,427660606,17984633,45.217322,-93.333463,"POLYGON ((-93.522465 45.197527, -93.5223719999...",Unified
126,27,10170,2710170,Delano Public School District,0,PK,12,G5420,NaN,E,160652653,7634118,45.040383,-93.769373,"MULTIPOLYGON (((-93.821767 45.102602, -93.8209...",Unified
127,27,11670,2711670,Minnetonka Public School District,0,PK,12,G5420,NaN,E,59506069,19840307,44.905019,-93.547625,"POLYGON ((-93.662308 44.891312, -93.659984 44....",Unified
128,27,14220,2714220,Eden Prairie Public School District,0,PK,12,G5420,NaN,E,80938340,7075778,44.846851,-93.457341,POLYGON ((-93.52093099999999 44.82666299999999...,Unified
129,27,22920,2722920,Westonka Public School District,0,PK,12,G5420,NaN,E,50289734,25251180,44.939649,-93.665103,"POLYGON ((-93.738355 44.981501, -93.7370859999...",Unified
130,27,25200,2725200,Osseo Public School District,0,PK,12,G5420,NaN,E,161668520,7854774,45.107973,-93.430411,"POLYGON ((-93.553798 45.120107999999995, -93.5...",Unified
131,27,42160,2742160,Wayzata Public School District,0,PK,12,G5420,NaN,E,103829620,7918157,45.010205,-93.499106,"POLYGON ((-93.59543699999999 45.051057, -93.59...",Unified
205,27,5790,2705790,Bloomington Public School District,0,PK,12,G5420,NaN,E,89187708,9560896,44.829666,-93.315217,POLYGON ((-93.39890199999999 44.84079099999999...,Unified
206,27,32070,2732070,Rockford Public School District,0,PK,12,G5420,NaN,E,109955878,3283294,45.103722,-93.674218,"MULTIPOLYGON (((-93.781238 45.12987, -93.77846...",Unified
271,27,6240,2706240,Brooklyn Center School District,0,PK,12,G5420,NaN,E,7100587,202591,45.067676,-93.302089,"POLYGON ((-93.320026 45.078976999999995, -93.3...",Unified

In [71]:
len(HC_district_wkt['GEOID'].unique())

23

In [72]:
HC_district_wkt.to_csv(r'/Users/miana/Downloads/Neo4j_clean_data/HC_district_wkt.csv', index = False, header=True)

In [73]:
len(HC_district_wkt)

23

In [74]:
pd.read_csv('/Users/miana/Downloads/un_district_wkt.csv')

,Unnamed: 0,STATEFP,UNSDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,FUNCSTAT,...,INTPTLON,g_wkt_final,districtId,name,student_pop,avg_eng,avg_math,avg_read,avg_sci,avg_ACT
0,0,27,3180,2703180,Anoka-Hennepin Public,0,PK,12,G5420,E,...,-93.333463,"POLYGON ((-93.522465 45.197527, -93.5223719999...",d2703180,Anoka-Hennepin Public,2854,19,21,21,21,21
1,1,27,10170,2710170,Delano Public,0,PK,12,G5420,E,...,-93.769373,"MULTIPOLYGON (((-93.821767 45.102602, -93.8209...",d2710170,Delano Public,142,22,25,24,24,24
2,2,27,11670,2711670,Minnetonka Public,0,PK,12,G5420,E,...,-93.547625,"POLYGON ((-93.662308 44.891312, -93.659984 44....",d2711670,Minnetonka Public,719,26,25,27,26,26
3,3,27,14220,2714220,Eden Prairie Public,0,PK,12,G5420,E,...,-93.457341,POLYGON ((-93.52093099999999 44.82666299999999...,d2714220,Eden Prairie Public,718,24,24,24,24,24
4,4,27,22920,2722920,Westonka Public,0,PK,12,G5420,E,...,-93.665103,"POLYGON ((-93.738355 44.981501, -93.7370859999...",d2722920,Westonka Public,157,23,23,24,23,23
5,5,27,25200,2725200,Osseo Public,0,PK,12,G5420,E,...,-93.430411,"POLYGON ((-93.553798 45.120107999999995, -93.5...",d2725200,Osseo Public,1559,19,20,20,20,20
6,6,27,42160,2742160,Wayzata Public,0,PK,12,G5420,E,...,-93.499106,"POLYGON ((-93.59543699999999 45.051057, -93.59...",d2742160,Wayzata Public,824,25,26,26,26,26
7,7,27,5790,2705790,Bloomington Public,0,PK,12,G5420,E,...,-93.315217,POLYGON ((-93.39890199999999 44.84079099999999...,d2705790,Bloomington Public,746,20,22,22,21,21
8,8,27,32070,2732070,Rockford Public,0,PK,12,G5420,E,...,-93.674218,"MULTIPOLYGON (((-93.781238 45.12987, -93.77846...",d2732070,Rockford Public,74,21,23,23,22,22
9,9,27,6240,2706240,Brooklyn Center,0,PK,12,G5420,E,...,-93.302089,"POLYGON ((-93.320026 45.078976999999995, -93.3...",d2706240,Brooklyn Center,145,14,16,16,17,16
10,10,27,7200,2707200,Buffalo-Hanover-Montrose Public,0,PK,12,G5420,E,...,-93.816639,"MULTIPOLYGON (((-93.767296 45.111846, -93.7672...",d2707200,Buffalo-Hanover-Montrose Public,428,21,22,22,22,22
11,11,27,14260,2714260,Hopkins Public,0,PK,12,G5420,E,...,-93.412482,POLYGON ((-93.48338299999999 44.89889499999999...,d2714260,Hopkins Public,521,22,22,23,22,22
12,12,27,31750,2731750,Richfield Public,0,PK,12,G5420,E,...,-93.287366,"POLYGON ((-93.339084 44.886677999999996, -93.3...",d2731750,Richfield Public,257,17,19,19,19,19
13,13,27,33420,2733420,St. Anthony-New Brighton Public,0,PK,12,G5420,E,...,-93.215417,"POLYGON ((-93.227068 45.047847, -93.227059 45....",d2733420,St. Anthony-New Brighton Public,167,23,22,23,23,23
14,14,27,33780,2733780,St. Louis Park Public,0,PK,12,G5420,E,...,-93.363762,"POLYGON ((-93.40077199999999 44.941841, -93.40...",d2733780,St. Louis Park Public,336,21,21,22,22,22
15,15,27,41460,2741460,Waconia Public,0,PK,12,G5420,E,...,-93.799814,"POLYGON ((-94.01226899999999 44.906068, -94.00...",d2741460,Waconia Public,310,22,23,23,23,23
16,16,27,41910,2741910,Watertown-Mayer Public,0,PK,12,G5420,E,...,-93.883077,"MULTIPOLYGON (((-93.711556 44.92051, -93.70644...",d2741910,Watertown-Mayer Public,80,20,22,22,22,22
17,17,27,8190,2708190,Eastern Carver County Public,0,PK,12,G5420,E,...,-93.637918,"POLYGON ((-93.745437 44.789274999999996, -93.7...",d2708190,Eastern Carver County Public,789,22,23,23,23,23
18,18,27,11250,2711250,Edina Public,0,PK,12,G5420,E,...,-93.357823,"POLYGON ((-93.401341 44.904605, -93.4013 44.90...",d2711250,Edina Public,646,27,25,27,26,26
19,19,27,21240,2721240,Minneapolis Public,0,PK,12,G5420,E,...,-93.268320,"POLYGON ((-93.329163 44.941421999999996, -93.3...",d2721240,Minneapolis Public,2090,18,19,19,19,19
20,20,27,25080,2725080,Orono Public,0,PK,12,G5420,E,...,-93.610104,POLYGON ((-93.73834599999999 45.00633699999999...,d2725080,Orono Public,224,25,25,25,25,25
21,21,27,31780,2731780,Robbinsdale Public,0,PK,12,G5420,E,...,-93.378405,"POLYGON ((-93.472269 45.023865, -93.472071 45....",d2731780,Robbinsdale Public,844,18,19,19,19,19
22,22,27,11370,2711370,Elk River Public,0,PK,12,G5420,E,...,-93.572212,"MULTIPOLYGON (((-93.45234099999999 45.291031, ...",d2711370,Elk River Public,881,20,22,22,22,21

In [1]:
import pandas as pd
import numpy as np
import geopandas

In [7]:
district = pd.read_csv('/Users/miana/Downloads/Neo4j_clean_data/HC_district_wkt.csv')

In [3]:
district.head(10)

,STATEFP,SDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,g_wkt_final,school_district_type
0,27,3180,2703180,Anoka-Hennepin Public School District,0,PK,12,G5420,NaN,E,427660606,17984633,45.217322,-93.333463,"POLYGON ((-93.522465 45.197527, -93.5223719999...",Unified
1,27,10170,2710170,Delano Public School District,0,PK,12,G5420,NaN,E,160652653,7634118,45.040383,-93.769373,"MULTIPOLYGON (((-93.821767 45.102602, -93.8209...",Unified
2,27,11670,2711670,Minnetonka Public School District,0,PK,12,G5420,NaN,E,59506069,19840307,44.905019,-93.547625,"POLYGON ((-93.662308 44.891312, -93.659984 44....",Unified
3,27,14220,2714220,Eden Prairie Public School District,0,PK,12,G5420,NaN,E,80938340,7075778,44.846851,-93.457341,POLYGON ((-93.52093099999999 44.82666299999999...,Unified
4,27,22920,2722920,Westonka Public School District,0,PK,12,G5420,NaN,E,50289734,25251180,44.939649,-93.665103,"POLYGON ((-93.738355 44.981501, -93.7370859999...",Unified
5,27,25200,2725200,Osseo Public School District,0,PK,12,G5420,NaN,E,161668520,7854774,45.107972,-93.430411,"POLYGON ((-93.553798 45.120107999999995, -93.5...",Unified
6,27,42160,2742160,Wayzata Public School District,0,PK,12,G5420,NaN,E,103829620,7918157,45.010205,-93.499106,"POLYGON ((-93.59543699999999 45.051057, -93.59...",Unified
7,27,5790,2705790,Bloomington Public School District,0,PK,12,G5420,NaN,E,89187708,9560896,44.829666,-93.315217,POLYGON ((-93.39890199999999 44.84079099999999...,Unified
8,27,32070,2732070,Rockford Public School District,0,PK,12,G5420,NaN,E,109955878,3283294,45.103722,-93.674218,"MULTIPOLYGON (((-93.781238 45.12987, -93.77846...",Unified
9,27,6240,2706240,Brooklyn Center School District,0,PK,12,G5420,NaN,E,7100587,202591,45.067676,-93.302089,"POLYGON ((-93.320026 45.078976999999995, -93.3...",Unified

In [9]:
gdf = geopandas.GeoDataFrame(
    district, geometry=geopandas.points_from_xy(district.INTPTLAT, district.INTPTLON))

In [10]:
gdf.head(10)

,STATEFP,SDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,g_wkt_final,school_district_type,geometry
0,27,3180,2703180,Anoka-Hennepin Public School District,0,PK,12,G5420,NaN,E,427660606,17984633,45.217322,-93.333463,"POLYGON ((-93.522465 45.197527, -93.5223719999...",Unified,POINT (45.217 -93.333)
1,27,10170,2710170,Delano Public School District,0,PK,12,G5420,NaN,E,160652653,7634118,45.040383,-93.769373,"MULTIPOLYGON (((-93.821767 45.102602, -93.8209...",Unified,POINT (45.040 -93.769)
2,27,11670,2711670,Minnetonka Public School District,0,PK,12,G5420,NaN,E,59506069,19840307,44.905019,-93.547625,"POLYGON ((-93.662308 44.891312, -93.659984 44....",Unified,POINT (44.905 -93.548)
3,27,14220,2714220,Eden Prairie Public School District,0,PK,12,G5420,NaN,E,80938340,7075778,44.846851,-93.457341,POLYGON ((-93.52093099999999 44.82666299999999...,Unified,POINT (44.847 -93.457)
4,27,22920,2722920,Westonka Public School District,0,PK,12,G5420,NaN,E,50289734,25251180,44.939649,-93.665103,"POLYGON ((-93.738355 44.981501, -93.7370859999...",Unified,POINT (44.940 -93.665)
5,27,25200,2725200,Osseo Public School District,0,PK,12,G5420,NaN,E,161668520,7854774,45.107972,-93.430411,"POLYGON ((-93.553798 45.120107999999995, -93.5...",Unified,POINT (45.108 -93.430)
6,27,42160,2742160,Wayzata Public School District,0,PK,12,G5420,NaN,E,103829620,7918157,45.010205,-93.499106,"POLYGON ((-93.59543699999999 45.051057, -93.59...",Unified,POINT (45.010 -93.499)
7,27,5790,2705790,Bloomington Public School District,0,PK,12,G5420,NaN,E,89187708,9560896,44.829666,-93.315217,POLYGON ((-93.39890199999999 44.84079099999999...,Unified,POINT (44.830 -93.315)
8,27,32070,2732070,Rockford Public School District,0,PK,12,G5420,NaN,E,109955878,3283294,45.103722,-93.674218,"MULTIPOLYGON (((-93.781238 45.12987, -93.77846...",Unified,POINT (45.104 -93.674)
9,27,6240,2706240,Brooklyn Center School District,0,PK,12,G5420,NaN,E,7100587,202591,45.067676,-93.302089,"POLYGON ((-93.320026 45.078976999999995, -93.3...",Unified,POINT (45.068 -93.302)

In [11]:
district = district.rename(columns={"geometry": "PointWKT"})

In [12]:
district.head(10)

,STATEFP,SDLEA,GEOID,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,g_wkt_final,school_district_type,PointWKT
0,27,3180,2703180,Anoka-Hennepin Public School District,0,PK,12,G5420,NaN,E,427660606,17984633,45.217322,-93.333463,"POLYGON ((-93.522465 45.197527, -93.5223719999...",Unified,POINT (45.217 -93.333)
1,27,10170,2710170,Delano Public School District,0,PK,12,G5420,NaN,E,160652653,7634118,45.040383,-93.769373,"MULTIPOLYGON (((-93.821767 45.102602, -93.8209...",Unified,POINT (45.040 -93.769)
2,27,11670,2711670,Minnetonka Public School District,0,PK,12,G5420,NaN,E,59506069,19840307,44.905019,-93.547625,"POLYGON ((-93.662308 44.891312, -93.659984 44....",Unified,POINT (44.905 -93.548)
3,27,14220,2714220,Eden Prairie Public School District,0,PK,12,G5420,NaN,E,80938340,7075778,44.846851,-93.457341,POLYGON ((-93.52093099999999 44.82666299999999...,Unified,POINT (44.847 -93.457)
4,27,22920,2722920,Westonka Public School District,0,PK,12,G5420,NaN,E,50289734,25251180,44.939649,-93.665103,"POLYGON ((-93.738355 44.981501, -93.7370859999...",Unified,POINT (44.940 -93.665)
5,27,25200,2725200,Osseo Public School District,0,PK,12,G5420,NaN,E,161668520,7854774,45.107972,-93.430411,"POLYGON ((-93.553798 45.120107999999995, -93.5...",Unified,POINT (45.108 -93.430)
6,27,42160,2742160,Wayzata Public School District,0,PK,12,G5420,NaN,E,103829620,7918157,45.010205,-93.499106,"POLYGON ((-93.59543699999999 45.051057, -93.59...",Unified,POINT (45.010 -93.499)
7,27,5790,2705790,Bloomington Public School District,0,PK,12,G5420,NaN,E,89187708,9560896,44.829666,-93.315217,POLYGON ((-93.39890199999999 44.84079099999999...,Unified,POINT (44.830 -93.315)
8,27,32070,2732070,Rockford Public School District,0,PK,12,G5420,NaN,E,109955878,3283294,45.103722,-93.674218,"MULTIPOLYGON (((-93.781238 45.12987, -93.77846...",Unified,POINT (45.104 -93.674)
9,27,6240,2706240,Brooklyn Center School District,0,PK,12,G5420,NaN,E,7100587,202591,45.067676,-93.302089,"POLYGON ((-93.320026 45.078976999999995, -93.3...",Unified,POINT (45.068 -93.302)

In [13]:
district.to_csv(r'/Users/miana/Downloads/Neo4j_clean_data/HC_district_wkt.csv', index = False, header=True)